#file: noinspection SpringBootApplicationYaml
#spring.application.name=ecom-application

spring:
  application:
    name: ecom-application

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: MyNewApp
    description: App build by us
    version: 1.0.0

